volumes:
  postgres_data:

services:

  sistema:
      build:
        context: ./sistema
      container_name: api_sistema
      ports:
        - "8000:8000"
      depends_on:
        - db


  db:
    image: postgres:13
    container_name: sistema_postgres_container
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

